frontend:
  - changed-files:
    - any-glob-to-any-file: ['ui/src/**/*']

backend:
  - changed-files:
    - any-glob-to-any-file: ['src/**/*']

documentation:
  - changed-files:
    - any-glob-to-any-file: ['README.md', 'CONTRIBUTING.md', '**/*.md']

dependencies:
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'package-lock.json']

ci/cd:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']

styling:
  - changed-files:
    - any-glob-to-any-file: ['index.css', 'tailwind.config.*']
